#!/usr/bin/env python3
"""Build CATALOGUE.md, the index the open-design-guide skill reads.

Usage: build-catalogue.py <library-root>

Walks the Open Design content dirs and writes <library-root>/CATALOGUE.md.
Design systems get their real one-line tagline from the top of DESIGN.md,
not the boilerplate in manifest.json. Skills that are only upstream stubs
are left out.
"""
import io
import os
import re
import sys
from collections import OrderedDict

STUB_MAX = 2500  # a SKILL.md smaller than this whose frontmatter only points
                 # upstream carries no instructions of its own


def frontmatter_description(path):
    try:
        text = open(path, encoding="utf-8").read()
    except OSError:
        return ""
    head = re.match(r"^---\n(.*?)\n---", text, re.S)
    if not head:
        return ""
    found = re.search(
        r"^description:\s*(?:\|[-> ]*\s*\n\s*)?[\"']?(.+?)[\"']?\s*$",
        head.group(1), re.M)
    return re.sub(r"\s+", " ", found.group(1)).strip() if found else ""


def is_stub(path):
    try:
        text = open(path, encoding="utf-8").read()
    except OSError:
        return True
    parts = text.split("---")
    return len(parts) > 1 and "upstream:" in parts[1] and os.path.getsize(path) < STUB_MAX


def design_systems(root):
    """name -> (category, tagline), read from the DESIGN.md blockquote header."""
    by_category = OrderedDict()
    base = os.path.join(root, "design-systems")
    for name in sorted(os.listdir(base)):
        design_md = os.path.join(base, name, "DESIGN.md")
        if not os.path.isfile(design_md):
            continue
        head = open(design_md, encoding="utf-8").read(1200)
        category = re.search(r"^>\s*Category:\s*(.+)$", head, re.M)
        quotes = [line[1:].strip() for line in head.splitlines()
                  if line.startswith(">") and "Category:" not in line and line[1:].strip()]
        tagline = re.sub(r"\s+", " ", quotes[0]).strip()[:88] if quotes else ""
        key = category.group(1).strip() if category else "Uncategorized"
        by_category.setdefault(key, []).append((name, tagline))
    return by_category


def skill_dirs(root, subdir, skip_stubs):
    base = os.path.join(root, subdir)
    if not os.path.isdir(base):
        return []
    out = []
    for name in sorted(os.listdir(base)):
        skill_md = os.path.join(base, name, "SKILL.md")
        if not os.path.isfile(skill_md):
            continue
        if skip_stubs and is_stub(skill_md):
            continue
        out.append((name, frontmatter_description(skill_md)[:88]))
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: build-catalogue.py <library-root>")
    root = os.path.abspath(sys.argv[1])
    if not os.path.isdir(os.path.join(root, "design-systems")):
        sys.exit("not an Open Design library: %s" % root)

    systems = design_systems(root)
    skills = skill_dirs(root, "skills", skip_stubs=True)
    templates = skill_dirs(root, "design-templates", skip_stubs=False)
    all_skill_dirs = len([d for d in os.listdir(os.path.join(root, "skills"))
                          if os.path.isfile(os.path.join(root, "skills", d, "SKILL.md"))])
    total_systems = sum(len(v) for v in systems.values())

    out = io.StringIO()
    w = out.write
    w("# Open Design catalogue\n\n")
    w("Generated by `open-design-guide`. Do not edit by hand: rerun the install script.\n\n")
    w("Library root: `%s`\n" % root)
    w("\n## Design systems (%d)\n\n" % total_systems)
    w("Each at `design-systems/<name>/`. `DESIGN.md` is the brand contract and the only file "
      "you must read. Alongside it: `tokens.css`, `design-tokens.json`, `tailwind-v4.css`, "
      "`components.html`, `components.manifest.json`, `USAGE.md`. Translated `DESIGN-<lang>.md` "
      "copies exist for 16 languages.\n")
    for category in sorted(systems):
        w("\n### %s\n\n" % category)
        for name, tagline in sorted(systems[category]):
            w("- `%s`%s\n" % (name, (" - " + tagline) if tagline else ""))
    w("\n## Skills (%d)\n\n" % len(skills))
    w("Each at `skills/<name>/SKILL.md`. Read the whole file before acting on it.\n\n")
    for name, desc in skills:
        w("- `%s`%s\n" % (name, (" - " + desc) if desc else ""))
    w("\n## Design templates (%d)\n\n" % len(templates))
    w("Rendering shapes for decks, editorial documents, video frames, mockups, and social "
      "cards. Each at `design-templates/<name>/SKILL.md`.\n\n")
    for name, desc in templates:
        w("- `%s`%s\n" % (name, (" - " + desc) if desc else ""))
    w("\n## Deliberately excluded\n\n")
    w("%d other folders under `skills/` are catalogue stubs: frontmatter plus a link to an "
      "upstream repo, with no instructions of their own. They are not listed above. If one is "
      "asked for by name, open its `SKILL.md` for the upstream URL.\n"
      % (all_skill_dirs - len(skills)))

    target = os.path.join(root, "CATALOGUE.md")
    open(target, "w", encoding="utf-8").write(out.getvalue())
    print("%s: %d systems, %d skills, %d templates" %
          (target, total_systems, len(skills), len(templates)))


if __name__ == "__main__":
    main()
