#!/usr/bin/env node
'use strict';
/**
 * Writes hooks/kit.md and hooks/kit-inline.md from assets/rc.css and
 * assets/blocks.md.
 *
 *   node readable/tools/gen-kit.js          rewrite both files
 *   node readable/tools/gen-kit.js --check   exit 1 if either is out of date
 *
 * Both were hand-written until 6.7.0, and both had to be re-typed whenever the
 * sheet or the vocabulary moved. They had drifted from the card tool's own
 * description in both directions, and kit.md's CDN line was pinned to a release
 * two versions behind the plugin — a card that silently painted with old CSS,
 * with nothing to fail. test.js runs --check, so the files cannot be stale for
 * longer than one test run.
 *
 * The CDN ref is a BRANCH, not a release tag. A tag ref is immutable, which is
 * the argument for it, but "Shipping is a push" (CLAUDE.md) has no tag step in
 * it, so a tag ref is a promise the release flow does not keep: the pinned tag
 * either lags the plugin, as it did, or names a tag nobody pushed, and that one
 * 404s and the card paints unstyled. A branch ref cannot 404 and cannot lag.
 */
const fs = require('fs');
const path = require('path');
const kit = require('../server/kit.js');
const blocks = require('../server/blocks.js');

const HOOKS = path.join(__dirname, '..', 'hooks');
const CDN = "@import url('https://cdn.jsdelivr.net/gh/smk-labs/claude-plugins@main/readable/assets/rc.css');";

/* BASE as the model must copy it: comments gone (they are for maintainers), one
 * rule per line (it is transcribed by hand on this path, and a single line of
 * 9KB is where a copy goes wrong), and unframed: the widget host draws the cell,
 * so BASE must not draw a second box inside it. */
const BASE = kit.unframed(kit.stripComments(kit.base()).replace(/\n{2,}/g, '\n').trim());

const SKELETON = ['<div class="rc" dir="rtl">', '<style>', BASE, '</style>', 'CONTENT', '</div>'].join('\n');

function header(inline) {
  return '<!-- TIER 2 KIT' + (inline ? ', OFFLINE' : '') + '. GENERATED by tools/gen-kit.js from assets/rc.css + ' +
    'assets/blocks.md — do not edit, edit those and regenerate (test.js fails on drift). ' +
    (inline ? 'Every component inline, for a host that cannot reach a CDN. ' : 'Component CSS comes from a CDN branch ref, so it can neither lag the plugin nor 404 on an unpushed tag; BASE stays inline as the offline floor. If a card paints unstyled the CDN is unreachable: use kit-inline.md, which needs no network. ') +
    'Read on demand by hooks/rule.md when the host has a widget tool but no `card` tool; never injected at SessionStart, because most sessions never reach tier 2. -->';
}

/* One component, prose then (offline path only) the CSS it owns. */
function component(entry, inline) {
  const prose = '- ' + blocks.describe(entry, true);
  if (!inline) return prose;
  const css = kit.snippets().filter((s) => blocks.tagsOf(entry).indexOf(s.tag) !== -1)
    .map((s) => kit.stripComments(s.css).replace(/\n{2,}/g, '\n').trim()).join('\n');
  return prose + '\n\n' + css;
}

function build(inline) {
  const entries = blocks.chat(2).filter((e) => !(inline && e.skip && e.skip.indexOf('inline') === 0));
  const skipped = blocks.chat(2).filter((e) => inline && e.skip && e.skip.indexOf('inline') === 0);
  const parts = [
    header(inline),
    '<readable-widget-kit>',
    blocks.section('lead tier2'),
    blocks.section(inline ? 'skeleton inline' : 'skeleton cdn').replace('{{SKELETON}}', SKELETON),
    blocks.section('text'),
    /* Derived, not written twice: an entry that names a path it must not reach
     * says why in blocks.md, and the reason is delivered on that path. */
    ...skipped.map((e) => 'The ' + e.tag + ' component is deliberately absent from this path: ' + e.skip.replace(/^inline\s*—\s*/, '')),
    blocks.section(inline ? 'css inline' : 'css cdn').replace('{{IMPORT}}', CDN),
    entries.map((e) => component(e, inline)).join('\n\n'),
    blocks.section('guidance'),
    blocks.section('close tier2').replace('{{SIGNATURE}}', kit.signature()),
    '</readable-widget-kit>',
  ];
  return parts.join('\n\n').replace(/\n{3,}/g, '\n\n') + '\n';
}

const TARGETS = [
  { file: path.join(HOOKS, 'kit.md'), text: build(false) },
  { file: path.join(HOOKS, 'kit-inline.md'), text: build(true) },
];

if (process.argv.indexOf('--check') !== -1) {
  const stale = TARGETS.filter((t) => {
    let have = '';
    try { have = fs.readFileSync(t.file, 'utf8').replace(/\r\n/g, '\n'); } catch (e) { have = ''; }
    return have !== t.text;
  });
  if (stale.length) {
    process.stderr.write('stale, run `node readable/tools/gen-kit.js`:\n  ' +
      stale.map((t) => path.basename(t.file)).join('\n  ') + '\n');
    process.exit(1);
  }
  process.stdout.write('kit.md and kit-inline.md are up to date\n');
  process.exit(0);
}

for (const t of TARGETS) {
  fs.writeFileSync(t.file, t.text);
  process.stdout.write('wrote ' + path.relative(path.join(__dirname, '..', '..'), t.file) + ' (' + t.text.length + ' bytes)\n');
}
